###
GET http://localhost:8000/api/startups

###
GET http://localhost:8000/api/startups/4


###
GET http://localhost:8000/api/selections

###
GEt http://localhost:8000/api/startups/search?searchKeyword=코