###
GET http://localhost:8000/api/startups

###
GET http://localhost:8000/api/startups/4

###
GET http://localhost:8000/api/startups/72/rank

###
GET http://localhost:8000/api/selections

###
GEt http://localhost:8000/api/startups/search?order=simInvestDesc&searchKeyword=코

###

GET http://localhost:8000/api/startups/comparison?startupId=5&compareIds=48,17,15&order=employeesAsc

//asc: 오름차순, desc:내림차순, 사용되는 order는 actualInvest(누적 투자금액),revenue(매출액),employees(고용 인원)

###
PATCH http://localhost:8000/api/startups/selections?startupId=2&compareIds=4,8,17,25,33

###

PATCH http://localhost:8000/api/selections/1/myStartup

###
GET http://localhost:8000/api/investors?startupId=1&offset=0&limit=5

###
DELETE http://localhost:8000/api/investments/25
Content-Type: application/json

{
    "password": "pw1234"
}